[package]
name = "scratchstack-aspen"
description = "AWS IAM policy language (Aspen) parser and internam representation"
version = "0.1.0"
authors = ["David Cuthbert <dacut@kanga.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["AWS", "IAM", "Aspen", "policy"]
homepage = "https://github.com/dacut/scratchstack-aspen"
repository = "https://github.com/dacut/scratchstack-aspen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "scratchstack_aspen"

[dependencies]
lazy_static = "^1.4.0"
log = "^0.4"
regex = "^1.3"
scratchstack-aws-principal = { version = "^0.3", features = ["service"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[dev-dependencies]
env_logger = "^0.8"
test-env-log = "^0.2"